# Generated by Django 4.1.13 on 2024-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prochat', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytest',
            name='session',
            field=models.CharField(default='default_session', max_length=100),
        ),
    ]
